# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

"""Workload container (snap or ROCK/OCI)"""

import abc
import pathlib
import subprocess
import typing

import ops

if typing.TYPE_CHECKING:
    import relations.cos


class Path(pathlib.PurePosixPath, abc.ABC):
    """Workload container (snap or ROCK) filesystem path"""

    @property
    @abc.abstractmethod
    def relative_to_container(self) -> pathlib.PurePosixPath:
        """Path from container root (instead of machine root)

        Only differs from `self` on machine charm
        """

    @abc.abstractmethod
    def open(self, mode="r") -> typing.TextIO:
        """Open the file in read text mode."""
        assert mode == "r"

    @abc.abstractmethod
    def read_text(self) -> str:
        """Open the file in text mode, read it, and close the file."""

    @abc.abstractmethod
    def write_text(self, data: str):
        """Open the file in text mode, write to it, and close the file."""

    @abc.abstractmethod
    def unlink(self, *, missing_ok=False):
        """Remove this file or link."""

    @abc.abstractmethod
    def mkdir(self):
        """Create a new directory at this path."""

    @abc.abstractmethod
    def rmtree(self):
        """Recursively delete the directory tree at this path."""


class CalledProcessError(subprocess.CalledProcessError):
    """Command returned non-zero exit code"""

    # TODO python3.10 min version: Use `list` instead of `typing.List`
    def __init__(
        self, *, returncode: int, cmd: typing.List[str], output: str, stderr: str
    ) -> None:
        super().__init__(returncode=returncode, cmd=cmd, output=output, stderr=stderr)


class Container(abc.ABC):
    """Workload container (snap or ROCK)"""

    @property
    def router_config_directory(self) -> Path:
        """MySQL Router configuration directory"""
        return self.path("/etc/mysqlrouter")

    @property
    def router_config_file(self) -> Path:
        """MySQL Router configuration file

        Automatically generated by MySQL Router bootstrap
        """
        return self.router_config_directory / "mysqlrouter.conf"

    @property
    def rest_api_credentials_file(self) -> Path:
        """Credentials file for MySQL Router's REST API"""
        return self.router_config_directory / "rest_api_credentials"

    @property
    def rest_api_config_file(self) -> Path:
        """Configuration file for the REST API for MySQLRouter"""
        return self.router_config_directory / "router_rest_api.conf"

    @property
    def tls_config_file(self) -> Path:
        """Extra MySQL Router configuration file to enable TLS"""
        return self.router_config_directory / "tls.conf"

    def __init__(
        self,
        *,
        mysql_router_command: str,
        mysql_shell_command: str,
        mysql_router_password_command: str,
        unit_name: str,
    ) -> None:
        self._mysql_router_command = mysql_router_command
        self._mysql_shell_command = mysql_shell_command
        self._mysql_router_password_command = mysql_router_password_command
        self._unit_name = unit_name

    @property
    @abc.abstractmethod
    def ready(self) -> bool:
        """Whether container is ready

        Only applies to Kubernetes charm
        """

    @property
    @abc.abstractmethod
    def mysql_router_service_enabled(self) -> bool:
        """MySQL Router service status"""

    @property
    @abc.abstractmethod
    def mysql_router_exporter_service_enabled(self) -> bool:
        """MySQL Router exporter service status"""

    @abc.abstractmethod
    def update_mysql_router_service(self, *, enabled: bool, tls: bool = None) -> None:
        """Update and restart MySQL Router service.

        Args:
            enabled: Whether MySQL Router service is enabled
            tls: Whether TLS is enabled. Required if enabled=True
        """
        if enabled:
            assert tls is not None, "`tls` argument required when enabled=True"

    @abc.abstractmethod
    def update_mysql_router_exporter_service(
        self,
        *,
        enabled: bool,
        config: "relations.cos.ExporterConfig" = None,
        tls: bool = None,
        key_filename: str = None,
        certificate_filename: str = None,
        certificate_authority_filename: str = None,
    ) -> None:
        """Update and restart the MySQL Router exporter service.

        Args:
            enabled: Whether MySQL Router exporter service is enabled
            config: The configuration for MySQL Router exporter
            tls: Whether custom TLS is enabled on the unit
            key_filename: The TLS key filename
            certificate_filename: The TLS certificate filename
            certificate_authority_filename: The TLS certificate authority filename
        """
        if enabled and not config:
            raise ValueError("Missing MySQL Router exporter config")

        if tls and not (certificate_authority_filename and certificate_filename and key_filename):
            raise ValueError(
                "`key`, `certificate` and `certificate_authority` required when tls=True"
            )

    @abc.abstractmethod
    def upgrade(self, unit: ops.Unit) -> None:
        """Upgrade container version

        Only applies to machine charm
        """

    @abc.abstractmethod
    # TODO python3.10 min version: Use `list` instead of `typing.List`
    def _run_command(
        self,
        command: typing.List[str],
        *,
        timeout: typing.Optional[int],
        input: str = None,
    ) -> str:
        """Run command in container.

        Raises:
            CalledProcessError: Command returns non-zero exit code
        """

    # TODO python3.10 min version: Use `list` instead of `typing.List`
    def run_mysql_router(self, args: typing.List[str], *, timeout: int = None) -> str:
        """Run MySQL Router command.

        Raises:
            CalledProcessError: Command returns non-zero exit code
        """
        args.insert(0, self._mysql_router_command)
        return self._run_command(args, timeout=timeout)

    # TODO python3.10 min version: Use `list` instead of `typing.List`
    def run_mysql_shell(self, args: typing.List[str], *, timeout: int = None) -> str:
        """Run MySQL Shell command.

        Raises:
            CalledProcessError: Command returns non-zero exit code
        """
        args.insert(0, self._mysql_shell_command)
        return self._run_command(args, timeout=timeout)

    @abc.abstractmethod
    def path(self, *args) -> Path:
        """Container filesystem path"""

    def create_router_rest_api_credentials_file(self) -> None:
        """Creates a credentials file for the router rest api if it does not exist."""
        if not self.rest_api_credentials_file.exists():
            # create empty credentials file
            self.rest_api_credentials_file.write_text("")

    def set_mysql_router_rest_api_password(
        self, *, user: str, password: typing.Optional[str]
    ) -> None:
        """Set REST API credentials using the mysqlrouter_password command."""
        self.create_router_rest_api_credentials_file()

        if not password:
            users_credentials = self._run_command(
                [
                    self._mysql_router_password_command,
                    "list",
                    str(self.rest_api_credentials_file),
                ],
                timeout=30,
            )
            if user not in users_credentials:
                return

        action = "set" if password else "delete"
        self._run_command(
            [
                self._mysql_router_password_command,
                action,
                str(self.rest_api_credentials_file),
                user,
            ],
            input=password,
            timeout=30,
        )
